version: '3.1'

secrets:
  piHolePassword:
    external: true

services:
  pihole:
    container_name: PiHole
    image: pihole/pihole:latest
    secrets:
      - piHolePassword
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8140:80/tcp"
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: /run/secrets/piHolePassword
    volumes:
      - /media/Intranet-of-Things/Volumes/PiHole/etc-pihole/:/etc/pihole/
      - /media/Intranet-of-Things/Volumes/PiHole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: always
